PRODUCTS_ROUTE_URI: http://localhost:8081
CONTENT_ROUTE_URI: http://localhost:8082
USERS_ROUTE_URI: http://localhost:8083

spring:
  server: 8080
  cloud:
    gateway:
      routes:
        - id: products-route
          uri: ${PRODUCTS_ROUTE_URI}
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api
        - id: content-route
          uri: ${CONTENT_ROUTE_URI}
          predicates:
            - Path=/content/**
          filters:
            - PrefixPath=/api
        - id: user-route
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api

              
