CREATE SEQUENCE literals_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE content_table_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE images_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE icons_seq START WITH 1 INCREMENT BY 50;