curl \
-d '{
      "contentId": 0,
      "name": "main-page",
      "component": 2,
      "literals": [
        {"literalId": 0,
          "component": 2,
          "value": "Lorem ipsum dolor",
          "type": "welcome-1-header",
          "content": null},
        {"literalId": 1,
          "component": 2,
          "value": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac felis arcu. Nullam dictum mollis faucibus.",
          "type": "welcome-1-text",
          "content": null},
        {"literalId": 2,
          "component": 2,
          "value": "Lorem ipsum dolor",
          "type": "welcome-2-header",
          "content": null},
        {"literalId": 3,
          "component": 2,
          "value": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac felis arcu. Nullam dictum mollis faucibus.",
          "type": "welcome-2-text",
          "content": null},
        {"literalId": 4,
          "component": 2,
          "value": "Lorem ipsum dolor",
          "type": "welcome-3-header",
          "content": null},
        {"literalId": 5,
          "component": 2,
          "value": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac felis arcu. Nullam dictum mollis faucibus.",
          "type": "welcome-3-text",
          "content": null},
        {"literalId": 6,
          "component": 2,
          "value": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac felis arcu. Nullam dictum mollis faucibus.",
          "type": "welcome-3-button",
          "content": null},
        {"literalId": 7,
          "component": 2,
          "value": "Gorące okazje",
          "type": "promo-header",
          "content": null}
      ],
      "images": [
      {"imageId": 0,
        "component": 2,
        "url": "assets/main-page/promo-image.jpeg",
        "name": "promo-image.jpeg",
        "content": null},
        {"imageId": 1,
          "component": 2,
          "url": "assets/main-page/welcome-1-image.jpeg",
          "name": "welcome-1-image.jpeg",
          "content": null},
        {"imageId": 2,
          "component": 2,
          "url": "assets/main-page/welcome-2-image.jpeg",
          "name": "welcome-2-image.jpeg",
          "content": null},
        {"imageId": 3,
          "component": 2,
          "url": "assets/main-page/welcome-3-image.jpeg",
          "name": "welcome-3-image.jpeg",
          "content": null}
      ],
      "icons":[]
    }' \
-H 'Content-Type: application/json' \
-X POST http://localhost:8082/content